### PR TITLE
Supression of varaible opts_help 

### PR DESCRIPTION
**Pull request by Hugues-Antoine**
Hi,

I do not know if it's a good solution, but that rule this problem: https://github.com/docker/machine/issues/3583

### CODE REVIEW

**Comment by leonhartX** [comment]
Hi,
I can not reproduce this issue on my own environment, but it seems like the `opts_help` has some syntax problems.
could you try this change to see whether it can fix the issue?

change the `opts_help` definition from 

```
local opts_help="(- :)"{-h,--help}"[Print usage]"
```

to

```
local -a opts_help
opts_help=("(- :)--help[Print usage]")
```

**Comment by Hugues-Antoine** [comment]
Hi,

I tried your suggestion, but it does not work either.  
I reproduced the environment in a docker Image: https://hub.docker.com/r/huguesantoine/docker-machine-zsh-completion/

**Comment by leonhartX** [comment]
Thanks for the docker image!
I have made the change mentioned before to the image, and it seems to fix the issue. please check this:
`docker run -it --rm leonhart/zsh-completion-test zsh`

**Comment by Hugues-Antoine** [comment]
Thanks, it works on my environment :)

**Pull request closed without merging**
